name: Feature Request
description: Request/Suggest a feature.
title: "[Enhancement] "
labels: [enhancement]
body:
- type: markdown
  attributes:
      value: |
        Thanks for taking the time to suggest a new feature for this project!
- type: textarea
  attributes:
    label: Enhancement
    description: Describe your feature request/your idea here.
    placeholder: I would like to see...
  validations:
    required: true
- type: textarea
  attributes:
    label: Other information
    description: If you have other information, like mockups, etc., put them here.
    placeholder: Add other information here.
  validations:
    required: false