; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; Adapted for the luzwales/ColorPicker fork:
;  - exe is ColorPickerMax.exe (project assembly was renamed to avoid a
;    clash with the PixiEditor.ColorPicker NuGet assembly)
;  - single-file publish output is taken from ..\publish
;  - Xalyus Updater removed (that project no longer exists in this fork)
;  - version can be set at build time: ISCC /DMyAppVersion=x.y.z.w

#define MyAppName "ColorPicker Max"
#ifndef MyAppVersion
  #define MyAppVersion "6.9.1.2602"
#endif
#ifndef MyAppFullVersion
  #define MyAppFullVersion "6.9.1.2602"
#endif
#define MyAppPublisher "luzwales"
#define MyAppURL "https://github.com/luzwales/ColorPicker"
#define MyAppExeName "ColorPickerMax.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; A fork-specific GUID is used so it does not clash with upstream installs.
AppId={{4E1D7A8B-9C2F-4D3E-A1B6-5C8D7E9F0A2B}}
AppName={#MyAppName}
AppVersion={#MyAppFullVersion}
VersionInfoVersion={#MyAppVersion}
UninstallDisplayIcon={app}\{#MyAppExeName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=Output
OutputBaseFilename=ColorPickerMaxSetup
SetupIconFile=..\ColorPicker\CPM.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "Languages\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
