//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColorPicker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColorPicker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to bookmarks.
        /// </summary>
        public static string AddBookmark {
            get {
                return ResourceManager.GetString("AddBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a note.
        /// </summary>
        public static string AddNote {
            get {
                return ResourceManager.GetString("AddNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate colors with AI.
        /// </summary>
        public static string AIGenerateColor {
            get {
                return ResourceManager.GetString("AIGenerateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Generation.
        /// </summary>
        public static string AIGeneration {
            get {
                return ResourceManager.GetString("AIGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocean Breeze,Crimson Sunset,Enchanted Forest,Electric Dreams,Desert Mirage,Midnight Serenade,Neon Galaxy,Golden Harvest,Lavender Mist,Tropical Paradise,Fire and Ice,Mystic Moonlight,Emerald Elegance,Cherry Blossom,Aurora Australis,Steel City Lights,Vintage Romance,Sapphire Dreams,Amber Afterglow,Velvet Touch,Dandelion Wishes,Urban Jungle,Rose Petal Whispers,Icy Tundra,Chocolate Delight,Harbor Reflections,Whispering Wind,Vibrant Spectrum,Pastel Reverie,Moonlit Meadow.
        /// </summary>
        public static string AiPrompts {
            get {
                return ResourceManager.GetString("AiPrompts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize AI Generation settings..
        /// </summary>
        public static string AISettings {
            get {
                return ResourceManager.GetString("AISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to generate.
        /// </summary>
        public static string AmountToGenerate {
            get {
                return ResourceManager.GetString("AmountToGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analogous.
        /// </summary>
        public static string Analogous {
            get {
                return ResourceManager.GetString("Analogous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates are available..
        /// </summary>
        public static string AvailableUpdates {
            get {
                return ResourceManager.GetString("AvailableUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color details.
        /// </summary>
        public static string BackgroundDetails {
            get {
                return ResourceManager.GetString("BackgroundDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string BlueP {
            get {
                return ResourceManager.GetString("BlueP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the language of ColorPicker..
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change ColorPicker theme..
        /// </summary>
        public static string ChangeTheme {
            get {
                return ResourceManager.GetString("ChangeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on start.
        /// </summary>
        public static string CheckUpdatesOnStart {
            get {
                return ResourceManager.GetString("CheckUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromatic wheel.
        /// </summary>
        public static string ChromaticWheel {
            get {
                return ResourceManager.GetString("ChromaticWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMYK.
        /// </summary>
        public static string CMYK {
            get {
                return ResourceManager.GetString("CMYK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Options.
        /// </summary>
        public static string ColorOptions {
            get {
                return ResourceManager.GetString("ColorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The way ColorPicker handle colors..
        /// </summary>
        public static string ColorOptionsDesc {
            get {
                return ResourceManager.GetString("ColorOptionsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker.
        /// </summary>
        public static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker Max.
        /// </summary>
        public static string ColorPickerMax {
            get {
                return ResourceManager.GetString("ColorPickerMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracted colors will be displayed here..
        /// </summary>
        public static string ColorsWillDisplayHere {
            get {
                return ResourceManager.GetString("ColorsWillDisplayHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Tools.
        /// </summary>
        public static string ColorTools {
            get {
                return ResourceManager.GetString("ColorTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color is valid..
        /// </summary>
        public static string ColorValid {
            get {
                return ResourceManager.GetString("ColorValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma-separated (,).
        /// </summary>
        public static string CommaSeparated {
            get {
                return ResourceManager.GetString("CommaSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complementary.
        /// </summary>
        public static string Complementary {
            get {
                return ResourceManager.GetString("Complementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast Grid.
        /// </summary>
        public static string ContrastGrid {
            get {
                return ResourceManager.GetString("ContrastGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        public static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The converter feature of ColorPicker allows you to convert any color type to another one. The color types are RGB, HEX, HSV, HSL, CMYK, XYZ, YIQ and YUV. You can enter a color code in any of these formats and see the corresponding codes in the other formats..
        /// </summary>
        public static string ConverterInfo {
            get {
                return ResourceManager.GetString("ConverterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert from RGB.
        /// </summary>
        public static string ConvertFromRGB {
            get {
                return ResourceManager.GetString("ConvertFromRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy CMYK.
        /// </summary>
        public static string CopyCMYK {
            get {
                return ResourceManager.GetString("CopyCMYK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy color.
        /// </summary>
        public static string CopyColor {
            get {
                return ResourceManager.GetString("CopyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Decimal.
        /// </summary>
        public static string CopyDEC {
            get {
                return ResourceManager.GetString("CopyDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy HEX.
        /// </summary>
        public static string CopyHEX {
            get {
                return ResourceManager.GetString("CopyHEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy HSL.
        /// </summary>
        public static string CopyHSL {
            get {
                return ResourceManager.GetString("CopyHSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy HSV.
        /// </summary>
        public static string CopyHSV {
            get {
                return ResourceManager.GetString("CopyHSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy RGB.
        /// </summary>
        public static string CopyRGB {
            get {
                return ResourceManager.GetString("CopyRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy XYZ.
        /// </summary>
        public static string CopyXYZ {
            get {
                return ResourceManager.GetString("CopyXYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy YIQ.
        /// </summary>
        public static string CopyYIQ {
            get {
                return ResourceManager.GetString("CopyYIQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy YUV.
        /// </summary>
        public static string CopyYUV {
            get {
                return ResourceManager.GetString("CopyYUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation.
        /// </summary>
        public static string Creation {
            get {
                return ResourceManager.GetString("Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS.
        /// </summary>
        public static string CSS {
            get {
                return ResourceManager.GetString("CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your data and your privacy..
        /// </summary>
        public static string DataDescription {
            get {
                return ResourceManager.GetString("DataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data and Privacy.
        /// </summary>
        public static string DataPrivacy {
            get {
                return ResourceManager.GetString("DataPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEC.
        /// </summary>
        public static string DEC {
            get {
                return ResourceManager.GetString("DEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default color type.
        /// </summary>
        public static string DefaultColorType {
            get {
                return ResourceManager.GetString("DefaultColorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer tools.
        /// </summary>
        public static string DevTools {
            get {
                return ResourceManager.GetString("DevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string Disc {
            get {
                return ResourceManager.GetString("Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit in Selector.
        /// </summary>
        public static string EditInSelector {
            get {
                return ResourceManager.GetString("EditInSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit shortcut.
        /// </summary>
        public static string EditShortcut {
            get {
                return ResourceManager.GetString("EditShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a prompt to generate colors using the power of AI.
        /// </summary>
        public static string EmptyAiPlaceholder {
            get {
                return ResourceManager.GetString("EmptyAiPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty bookmarks.
        /// </summary>
        public static string EmptyBookmarks {
            get {
                return ResourceManager.GetString("EmptyBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to empty these bookmarks? This action is irreversible..
        /// </summary>
        public static string EmptyHistoryMsg {
            get {
                return ResourceManager.GetString("EmptyHistoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export settings.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportShort {
            get {
                return ResourceManager.GetString("ExportShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        public static string ExportToCSV {
            get {
                return ResourceManager.GetString("ExportToCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract colors.
        /// </summary>
        public static string ExtractColors {
            get {
                return ResourceManager.GetString("ExtractColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors are being extracted, please wait..
        /// </summary>
        public static string ExtractionInProgress {
            get {
                return ResourceManager.GetString("ExtractionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First color.
        /// </summary>
        public static string FirstColor {
            get {
                return ResourceManager.GetString("FirstColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to ignore this window and continue to ColorPicker?.
        /// </summary>
        public static string FirstRunQuitMsg {
            get {
                return ResourceManager.GetString("FirstRunQuitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string Foreground {
            get {
                return ResourceManager.GetString("Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground color details.
        /// </summary>
        public static string ForegroundDetails {
            get {
                return ResourceManager.GetString("ForegroundDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequence.
        /// </summary>
        public static string Frequence {
            get {
                return ResourceManager.GetString("Frequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a random color.
        /// </summary>
        public static string GenerateColor {
            get {
                return ResourceManager.GetString("GenerateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a gradient.
        /// </summary>
        public static string GenerateGradient {
            get {
                return ResourceManager.GetString("GenerateGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a palette.
        /// </summary>
        public static string GeneratePalette {
            get {
                return ResourceManager.GetString("GeneratePalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new colors.
        /// </summary>
        public static string GenerateTextColors {
            get {
                return ResourceManager.GetString("GenerateTextColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get contrast ratio.
        /// </summary>
        public static string GetContrast {
            get {
                return ResourceManager.GetString("GetContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get harmonies.
        /// </summary>
        public static string GetHarmonies {
            get {
                return ResourceManager.GetString("GetHarmonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ideas.
        /// </summary>
        public static string GetIdeas {
            get {
                return ResourceManager.GetString("GetIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon.
        /// </summary>
        public static string GoodAfternoon {
            get {
                return ResourceManager.GetString("GoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening.
        /// </summary>
        public static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good night.
        /// </summary>
        public static string GoodNight {
            get {
                return ResourceManager.GetString("GoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        public static string Gradient {
            get {
                return ResourceManager.GetString("Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gradient feature of ColorPicker lets you generate random two-stops gradients with a specific rotation angle. You can see a preview of the gradient and its CSS code. You can also export the gradient to CSS code and use it in your web design projects..
        /// </summary>
        public static string GradientInfo {
            get {
                return ResourceManager.GetString("GradientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradients.
        /// </summary>
        public static string Gradients {
            get {
                return ResourceManager.GetString("Gradients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string GreenP {
            get {
                return ResourceManager.GetString("GreenP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonies.
        /// </summary>
        public static string Harmonies {
            get {
                return ResourceManager.GetString("Harmonies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX.
        /// </summary>
        public static string HEX {
            get {
                return ResourceManager.GetString("HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight color.
        /// </summary>
        public static string HighlightColorGrid {
            get {
                return ResourceManager.GetString("HighlightColorGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSL.
        /// </summary>
        public static string HSL {
            get {
                return ResourceManager.GetString("HSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSV.
        /// </summary>
        public static string HSV {
            get {
                return ResourceManager.GetString("HSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hues.
        /// </summary>
        public static string Hues {
            get {
                return ResourceManager.GetString("Hues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Extractor.
        /// </summary>
        public static string ImageExtractor {
            get {
                return ResourceManager.GetString("ImageExtractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include frequence.
        /// </summary>
        public static string IncludeFrequence {
            get {
                return ResourceManager.GetString("IncludeFrequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To install updates, ColorPicker needs to restarts. Do you want to continue?.
        /// </summary>
        public static string InstallConfirmMsg {
            get {
                return ResourceManager.GetString("InstallConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install version.
        /// </summary>
        public static string InstallVersion {
            get {
                return ResourceManager.GetString("InstallVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing Synethia.
        /// </summary>
        public static string IntroducingSynethia {
            get {
                return ResourceManager.GetString("IntroducingSynethia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color is invalid..
        /// </summary>
        public static string InvalidColor {
            get {
                return ResourceManager.GetString("InvalidColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to start or stop selecting a color from your screen..
        /// </summary>
        public static string KeyboardSelectionHint {
            get {
                return ResourceManager.GetString("KeyboardSelectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard shortcuts.
        /// </summary>
        public static string KeyboardShortcuts {
            get {
                return ResourceManager.GetString("KeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go!.
        /// </summary>
        public static string LetsGo {
            get {
                return ResourceManager.GetString("LetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochromatic.
        /// </summary>
        public static string Monochromatic {
            get {
                return ResourceManager.GetString("Monochromatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker needs to restart to apply the changes..
        /// </summary>
        public static string NeedRestartLabel {
            get {
                return ResourceManager.GetString("NeedRestartLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker needs to restart to apply the changes. Do you want to restart now?.
        /// </summary>
        public static string NeedRestartToApplyChanges {
            get {
                return ResourceManager.GetString("NeedRestartToApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use AI featues, you need an OpenAI API key..
        /// </summary>
        public static string NoApiKeyMsg {
            get {
                return ResourceManager.GetString("NoApiKeyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thanks.
        /// </summary>
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications settings..
        /// </summary>
        public static string NotificationsDescription {
            get {
                return ResourceManager.GetString("NotificationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification when updates are available.
        /// </summary>
        public static string NotifyUpdates {
            get {
                return ResourceManager.GetString("NotifyUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors to diplay.
        /// </summary>
        public static string NumberColorDisplay {
            get {
                return ResourceManager.GetString("NumberColorDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On start.
        /// </summary>
        public static string OnStart {
            get {
                return ResourceManager.GetString("OnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings that applies on start..
        /// </summary>
        public static string OnStartDescription {
            get {
                return ResourceManager.GetString("OnStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenAI API Key.
        /// </summary>
        public static string OpenAIKey {
            get {
                return ResourceManager.GetString("OpenAIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palette.
        /// </summary>
        public static string Palette {
            get {
                return ResourceManager.GetString("Palette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palettes.
        /// </summary>
        public static string Palettes {
            get {
                return ResourceManager.GetString("Palettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picker.
        /// </summary>
        public static string Picker {
            get {
                return ResourceManager.GetString("Picker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned.
        /// </summary>
        public static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels.
        /// </summary>
        public static string Pixels {
            get {
                return ResourceManager.GetString("Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic updates are not available in portable mode, please download ColorPicker Max again..
        /// </summary>
        public static string PortableNoAutoUpdates {
            get {
                return ResourceManager.GetString("PortableNoAutoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision (pixels to ignore).
        /// </summary>
        public static string Precision {
            get {
                return ResourceManager.GetString("Precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a combination of keys..
        /// </summary>
        public static string PressKeys {
            get {
                return ResourceManager.GetString("PressKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please define an API Key in settings..
        /// </summary>
        public static string ProvideAPIKey {
            get {
                return ResourceManager.GetString("ProvideAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a prompt to AI..
        /// </summary>
        public static string ProvideAPromptMsg {
            get {
                return ResourceManager.GetString("ProvideAPromptMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string RedP {
            get {
                return ResourceManager.GetString("RedP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from bookmarks.
        /// </summary>
        public static string RemoveBookmark {
            get {
                return ResourceManager.GetString("RemoveBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove image.
        /// </summary>
        public static string RemoveImage {
            get {
                return ResourceManager.GetString("RemoveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset keyboard shortcuts.
        /// </summary>
        public static string ResetKeyboardShortcuts {
            get {
                return ResourceManager.GetString("ResetKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all settings?.
        /// </summary>
        public static string ResetSettingsConfirmation {
            get {
                return ResourceManager.GetString("ResetSettingsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Synethia data.
        /// </summary>
        public static string ResetSynethia {
            get {
                return ResourceManager.GetString("ResetSynethia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB.
        /// </summary>
        public static string RGB {
            get {
                return ResourceManager.GetString("RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB Separator.
        /// </summary>
        public static string RgbSeparator {
            get {
                return ResourceManager.GetString("RgbSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Rotation {
            get {
                return ResourceManager.GetString("Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.5+ (AA).
        /// </summary>
        public static string ScoreAA {
            get {
                return ResourceManager.GetString("ScoreAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7+ (AAA).
        /// </summary>
        public static string ScoreAAA {
            get {
                return ResourceManager.GetString("ScoreAAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ScoreAll {
            get {
                return ResourceManager.GetString("ScoreAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second color.
        /// </summary>
        public static string SecondColor {
            get {
                return ResourceManager.GetString("SecondColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See licenses.
        /// </summary>
        public static string SeeLicenses {
            get {
                return ResourceManager.GetString("SeeLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from the chromatic disc.
        /// </summary>
        public static string SelectChomaticDisc {
            get {
                return ResourceManager.GetString("SelectChomaticDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a color.
        /// </summary>
        public static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a format for each item..
        /// </summary>
        public static string SelectFormatItems {
            get {
                return ResourceManager.GetString("SelectFormatItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select images.
        /// </summary>
        public static string SelectImages {
            get {
                return ResourceManager.GetString("SelectImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector.
        /// </summary>
        public static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector feature of ColorPicker enables you to choose any color from the screen by moving the cursor over it and pressing a keyboard shortcut. The chosen color will be shown in a preview box and its code will be copied to the clipboard in a desired color type..
        /// </summary>
        public static string SelectorInfo {
            get {
                return ResourceManager.GetString("SelectorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-colon-separated (;).
        /// </summary>
        public static string SemiColonSeparated {
            get {
                return ResourceManager.GetString("SemiColonSeparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been sucessfully exported..
        /// </summary>
        public static string SettingsExportedSucessMsg {
            get {
                return ResourceManager.GetString("SettingsExportedSucessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were sucessfully imported. To finish the process, ColorPicker is going to restart..
        /// </summary>
        public static string SettingsImportedMsg {
            get {
                return ResourceManager.GetString("SettingsImportedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shades.
        /// </summary>
        public static string Shades {
            get {
                return ResourceManager.GetString("Shades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single color.
        /// </summary>
        public static string SingleColor {
            get {
                return ResourceManager.GetString("SingleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split Complementary.
        /// </summary>
        public static string SplitComplementary {
            get {
                return ResourceManager.GetString("SplitComplementary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start selection.
        /// </summary>
        public static string StartSelection {
            get {
                return ResourceManager.GetString("StartSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default page on start.
        /// </summary>
        public static string StartupPage {
            get {
                return ResourceManager.GetString("StartupPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steps.
        /// </summary>
        public static string Steps {
            get {
                return ResourceManager.GetString("Steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick actions.
        /// </summary>
        public static string SuggestedActions {
            get {
                return ResourceManager.GetString("SuggestedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synethia will then analyze this data to provide a unique experience.
        /// </summary>
        public static string SynethiaAnalyze {
            get {
                return ResourceManager.GetString("SynethiaAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synethia collects data in ColorPicker only.
        /// </summary>
        public static string SynethiaDataInfo {
            get {
                return ResourceManager.GetString("SynethiaDataInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all Synethia data? Your personalized experience will be lost; This action cannot be canceled..
        /// </summary>
        public static string SynethiaDeleteMsg {
            get {
                return ResourceManager.GetString("SynethiaDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Synethia customized experience..
        /// </summary>
        public static string SynethiaEnable {
            get {
                return ResourceManager.GetString("SynethiaEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Home dashbord will recommand actions based on your usage.
        /// </summary>
        public static string SynethiaHome {
            get {
                return ResourceManager.GetString("SynethiaHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synethia is an algorithm that personnalizes your experience..
        /// </summary>
        public static string SynethiaInfo {
            get {
                return ResourceManager.GetString("SynethiaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is stored on your device, anonymously. Absolutely NO data is sent to Léo Corporation..
        /// </summary>
        public static string SynethiaPrivacy {
            get {
                return ResourceManager.GetString("SynethiaPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextTool {
            get {
                return ResourceManager.GetString("TextTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text tool settings..
        /// </summary>
        public static string TextToolDesc {
            get {
                return ResourceManager.GetString("TextToolDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triadic.
        /// </summary>
        public static string Triadic {
            get {
                return ResourceManager.GetString("Triadic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColorPicker is up to date..
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use keyboard shortcuts.
        /// </summary>
        public static string UseKeyboardShortcuts {
            get {
                return ResourceManager.GetString("UseKeyboardShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use upper cases for HEX color.
        /// </summary>
        public static string UseUpperCasesHex {
            get {
                return ResourceManager.GetString("UseUpperCasesHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ColorPicker, the ultimate tool for picking, converting and generating colors..
        /// </summary>
        public static string WelcomeDesc {
            get {
                return ResourceManager.GetString("WelcomeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyting is ready.
        /// </summary>
        public static string WelcomeReady {
            get {
                return ResourceManager.GetString("WelcomeReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML.
        /// </summary>
        public static string XAML {
            get {
                return ResourceManager.GetString("XAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XYZ.
        /// </summary>
        public static string XYZ {
            get {
                return ResourceManager.GetString("XYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YIQ.
        /// </summary>
        public static string YIQ {
            get {
                return ResourceManager.GetString("YIQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YUV.
        /// </summary>
        public static string YUV {
            get {
                return ResourceManager.GetString("YUV", resourceCulture);
            }
        }
    }
}
